# ==========================================
# CONFIGURACIÓN GENERAL DE LA APLICACIÓN
# ==========================================
spring.application.name=PruebaTecnicaSupermercado
server.port=8080

# ==========================================
# CONFIGURACIÓN DE BASE DE DATOS (H2 EN MEMORIA)
# ==========================================
spring.datasource.url=jdbc:h2:mem:superdb;MODE=MySQL;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ==========================================
# CONFIGURACIÓN DE JPA / HIBERNATE
# ==========================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# 🚀 PROPIEDADES EXTRA: Te facilitan la vida mostrando el SQL real y formateado en consola
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==========================================
# INTERFAZ WEB DE H2 (H2 CONSOLE)
# ==========================================
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ==========================================
# ENTORNO DE PRODUCCIÓN / MYSQL (COMENTADO)
# ==========================================
# spring.datasource.url=${DB_URL}
# spring.datasource.username=${DB_USER_NAME}
# spring.datasource.password=${DB_PASSWORD}
# spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect